# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian9"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network "public_network", ip: "192.168.1.60"
  config.vm.define "worker-swarm"
end
